---
name: "Super-Linter slim"
author: "Super-linter contributors"
description: "Super-linter is a ready-to-run collection of linters and code analyzers, to help validate your source code."
runs:
  using: "docker"
  image: "docker://ghcr.io/super-linter/super-linter:slim-v9.0.0@sha256:7d0b4d3387deaac975e86e0787c7a05a25d530469b27d74c2b4599ab5800d9e4" # x-release-please-version
branding:
  icon: "check-square"
  color: "white"
# You can view https://github.com/super-linter/super-linter#environment-variables
# to see a comprehensive list of all environment variables that can be passed
